### ISSUE TITLE
[ENTREGA recuperatorioObjetos] 

### ISSUE THREAD

**Issue by AguSilva345** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-AguSilva345#1]
Juan Fernandes @juanFdS

**Comment by JuanFdS** [comment]
Parte A
---

- poderInnato se inicializa en 0 pero siempre tiene que ser del 1 al 10.
- El método poderQueAporta no hace nada, podría ser abstracto.
- Si la varita aporta un 50% extra, debería ser por 1,5.
- La ojota tiene que ser un objeto, ya que hay una sola, y debería multiplicarse por 10 y no por 2.
-  Al hacer otroMago.categoria().otroMetodo() se está rompiendo el encapsulamiento
- Entre MagoAprendiz y MagoVeterano hay repetición de lógica.

Parte B
---

- Falta implementar la reserva de energía mágica del gremio
- En puedeSerVencido se podrían hacer métodos auxiliares, pero la lógica está bien
- Falta usar la restricción de que un gremio debe tener al menos dos miembros
- No se contempla el enfrentamiento entre gremio y mago
- Falta el requisito que ahora los gremios pueden estar compuestos por magos y otros gremios

Nota: 6
